version: '3.1'

services:
  postgres:
    image: "postgres:14.1"
    ports:
      - "6080:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
#      - pg_data:/var/lib/postgresql/data
#  ololo:
#    build:
#      context: .

#volumes:
#  pg_data:



