version: '3.1'

services:
  postgres:
    image: "postgres:14.1"
    ports:
      - "6080:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users
    volumes:
      - pg_data:/var/lib/postgresql/data
  web-server:
    ports:
      - "8034:8034"
    build:
      context: .
    volumes:
      - ./cmd/signup-server:/cmd/signup-server

volumes:
  pg_data:



